name: Notify Integration Release (Tag)
on:
  push:
    tags:
      - '*.*.*'   # Semver
      - '*.*.*-*' # Pre Releases
jobs:
  notify-release:
    runs-on: ubuntu-latest
    steps:
      # TODO, this will be moved to a published action
      - name: Checkout integration-release-action
        uses: actions/checkout@v2
        with:
          repository: BrandonRomano/integration-release-action
          path: ./integration-release-action

      - name: Notify Release
        uses: ./integration-release-action
        with:
          integration_identifier: 'product/your-integration-here'
          release_version: ${{ github.ref_name }}
          release_sha: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
