name: Notify Integration Release (Manual)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version (semver)"
        default: 0.0.1
        required: false
      branch:
        description: "A branch or SHA"
        default: 'main'
        required: false
jobs:
  notify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout integration-release-action
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: hashicorp/integration-release-action
          path: ./integration-release-action
      - name: Notify Release
        uses: ./integration-release-action
        with:
          # integration_identifier should match the directory path of your
          # registration file in https://github.com/hashicorp/integrations.
          #
          # For example, looking at this registration file:
          # https://github.com/hashicorp/integrations/blob/main/waypoint/hashicorp/docker.hcl
          #                                                     ↑-----------------------↑
          # The integration identifier for this integration is `waypoint/hashicorp/docker`
          integration_identifier: 'product/organization/integration'
          release_version: ${{ github.event.inputs.version }}
          release_sha: ${{ github.event.inputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
